sonar.projectKey=bookstore
sonar.projectName=bookstore
sonar.host.url=http://localhost:9000
sonar.sourceEncoding=UTF-8

sonar.sources=frontend/src,backend/app,backend/routes,backend/public
sonar.exclusions=**/node_modules/**,**/vendor/**,**/dist/**,**/build/**,**/.scannerwork/**,**/public/build/**,**/storage/**,**/bootstrap/cache/**
