sonar.projectKey=bookstore
sonar.projectName=bookstore

sonar.host.url=http://localhost:9000
sonar.sourceEncoding=UTF-8

sonar.sources=frontend/src

# ONLY JS (no TS)
sonar.javascript.file.suffixes=.js,.jsx

# exclusions
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**